project:
  type: website

website:
  title: "ISSS626 Geospatial Analytics"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1.1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.1.html"
        - text: "Hands-on Exercise 1.2"
          href: "Hands-on_Ex/Hands-on_Ex01.2/Hands-on_Ex01.2.html"
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 1"
          href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
      
    
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

